### ISSUE TITLE
When resizing the window, should the cards go under each other?

### ISSUE THREAD

**Issue by Daniel12345rs01** [Yatokuri/Dunder-Mifflin_Infinity-3rd-Semester-Team-Drop-Table#19]
![image](https://github.com/user-attachments/assets/420e0949-908b-40a1-8c4d-02ebbccf73ce)

**Comment by NaylinHla** [comment]
Sure buddy

**Comment by NaylinHla** [comment]
PR: https://github.com/Yatokuri/Dunder-Mifflin_Infinity-3rd-Semester-Team-Drop-Table/pull/20
